#pragma once
enum mouseIndexes {
	QUIT = 0,
	MOUSEHELD = 1,
	LEFTMOUSEHELD = 11,
	RIGHTMOUSEHELD = 12,
	MIDDLEMOUSEHELD = 13,
	MOUSECLICKED = 2,
	LEFTMOUSECLICKED = 21,
	RIGHTMOUSECLICKED = 22,
	MIDDLEMOUSECLICKED = 23,

	MOUSEWHEELDOWN = 31,
	MOUSEWHEELUP = 32,

};